version: '3.5'

services:

  web:
    image: projectsidewalk/web
    container_name: projectsidewalk-web
    build:
      context: ./
    depends_on:
      - db
    volumes:
      - "./:/opt/:delegated"
      - "/opt/node_modules"
    ports:
      - "9000:9000"
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/sidewalk-newberg
      - SIDEWALK_CITY_ID=washington-dc
      - SIDEWALK_EMAIL_ADDRESS=DUMMY_EMAIL_ADDRESS
      - SIDEWALK_EMAIL_PASSWORD=DUMMY_EMAIL_PASSWORD
      - ENV_TYPE=test

  db:
    image: projectsidewalk/db
    container_name: projectsidewalk-db
    build:
      context: ./db/
    volumes:
      - "./db/init.sh:/docker-entrypoint-initdb.d/init.sh"
      - "./db:/opt"
    ports:
      - "5432:5432"
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sidewalk
